### ISSUE TITLE
IDF 6 support

### ISSUE THREAD

**Issue by luar123** [espressif/esp-zigbee-sdk#816]
### Is your feature request related to a problem?

When do you plan to add support for esp-idf 6.0? For new developments it would make much more sense to use the 2.0 zigbee sdk and target idf 6, so it is compatible with new variants like H4, H21.

### Describe the solution you'd like.

idf 6 support

**Comment by luar123** [comment]
Seems to work with v2.0.1 without any special settings. Thanks

**Comment by finalyards** [comment]
I wasn't as lucky. With the `examples/home_automation_devices/color_dimmer_switch` example, using ESP-IDF 6.0.1, I get:

```
$ CMAKE_BUILD_TYPE=Release idf.py build

...
[ 99%] Building C object esp-idf/espressif__esp-zigbee-lib/CMakeFiles/__idf_espressif__esp-zigbee-lib.dir/src/utils/esp_mbedtls.c.obj
/home/ubuntu/esp-zigbee-sdk/examples/home_automation_devices/color_dimmer_switch/managed_components/espressif__esp-zigbee-lib/src/utils/esp_mbedtls.c:7:10:fatal error: mbedtls/aes.h: No such file or directory
    7 | #include "mbedtls/aes.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [esp-idf/espressif__esp-zigbee-lib/CMakeFiles/__idf_espressif__esp-zigbee-lib.dir/build.make:93: esp-idf/espressif__esp-zigbee-lib/CMakeFiles/__idf_espressif__esp-zigbee-lib.dir/src/utils/esp_mbedtls.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:6213: esp-idf/espressif__esp-zigbee-lib/CMakeFiles/__idf_espressif__esp-zigbee-lib.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Missing "mbedtls/aes.h" file name found in the following component(s): openthread(/home/ubuntu/bin/esp-idf.6.0.1/components/openthread/openthread/third_party/mbedtls/repo/include/mbedtls/aes.h). Maybe one of the components needs to add the missing header directory to INCLUDE_DIRS of idf_component_register call in CMakeLists.txt. Another possibility may be that the component or its feature is not enabled in the configuration. Use "idf.py menuconfig" to check if the required options are enabled.
make failed with exit code 2, output of the command is in the /tmp/build.HA-color_dimmer_switch/log/idf_py_stderr_output_37952 and /tmp/build.HA-color_dimmer_switch/log/idf_py_stdout_output_37952
```
